// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo3I7a6cohWs4alERgGLOnDOK0W--jwzQ',
    appId: '1:1074092443502:web:58681bfb71498570c6e37f',
    messagingSenderId: '1074092443502',
    projectId: 'yacht-link-app-2026',
    authDomain: 'yacht-link-app-2026.firebaseapp.com',
    storageBucket: 'yacht-link-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByY1tZPui9boyggQ_SOPFEju7uL3YlqzY',
    appId: '1:1074092443502:android:24fcbb6fda89315dc6e37f',
    messagingSenderId: '1074092443502',
    projectId: 'yacht-link-app-2026',
    storageBucket: 'yacht-link-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeFCN8ItHqMHqgfu6SFYoEY0ip0fXLnJA',
    appId: '1:1074092443502:ios:8e2a7723e4503c8bc6e37f',
    messagingSenderId: '1074092443502',
    projectId: 'yacht-link-app-2026',
    storageBucket: 'yacht-link-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.yachtLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeFCN8ItHqMHqgfu6SFYoEY0ip0fXLnJA',
    appId: '1:1074092443502:ios:8e2a7723e4503c8bc6e37f',
    messagingSenderId: '1074092443502',
    projectId: 'yacht-link-app-2026',
    storageBucket: 'yacht-link-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.yachtLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo3I7a6cohWs4alERgGLOnDOK0W--jwzQ',
    appId: '1:1074092443502:web:fb2ebbb1afa4eed1c6e37f',
    messagingSenderId: '1074092443502',
    projectId: 'yacht-link-app-2026',
    authDomain: 'yacht-link-app-2026.firebaseapp.com',
    storageBucket: 'yacht-link-app-2026.firebasestorage.app',
  );
}
